### PR TITLE
Change example bot to work with slackclient>=2.0.

### PR DESCRIPTION
**Pull request by jeffFranklin**
###  Summary

Package slackclient  2.0 and beyond uses namespace `slack` in place of `slackclient`.
Use the equivalent `slack.WebClient`, and change the method call to use `slack.WebClient.chat_postMessage`. This is for the bot example code.

### Requirements (place an `x` in each `[ ]`)

* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by RodneyU215** [comment]
Right on @jeffFranklin! Thank you for this PR. 🙇 Before we merge this, would you mind updating the [ReadMe's Python requirements](https://github.com/slackapi/python-slack-events-api/blob/master/example/README.rst#--setup-and-running-the-app) to reflect your changes as well. We'd just have to remove the lines about Python 2.7 since the new SDK only supports Python 3.6+.

**Comment by jeffFranklin** [comment]
Thanks @RodneyU215! I've added a note about slackclient v2 to the README. I think python 3.6+ is the way to be, and it would simplify your documentation and make it even better. The part about virtualenv could go away, as it would get replaced with `python3 -m venv env`. I could make the change in my PR but I wouldn't want to muddle my initial change, plus your team might want to decide how to say it. Cheers!

**Comment by jeffFranklin** [comment]
Should I change the readme to be python3-specific in this PR? I could. It wasn't clear if you wanted that as part of this change. Thanks.

**Comment by seratch** [comment]
@jeffFranklin Thanks for your contribution! I'm sorry for taking a long time to merge this.

**Pull request merged**
