### PR TITLE
WIP: Send Slack request with event data (if handler asks for it)

### PR DESCRIPTION
**Pull request by datashaman**
Inspects arity of handler function to ascertain whether it should pass
request with _event_data_. Does not break current implementations.

Uses _inspect_ module to check arity of the first listener for a specific event type.

If you want an event handler to get the Slack request, define it like this:

    @adapter.on('reaction_added')
    def reaction_added(event_data, request):
        event = event_data['event']
        if request.headers.get('X-Slack-Retry-Num'):
            print('Event was retried')

**NB:** A side-effect of this is that all event handlers of the same type must have the same number of arguments!

Resolves https://github.com/slackapi/python-slack-events-api/issues/32
Requires (and is based on) https://github.com/slackapi/python-slack-events-api/pull/37

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by datashaman** [comment]
This could be changed to send just the headers, but I thought that the whole request might make it more useful.

**Comment by datashaman** [comment]
Please notify me if/when the base PR is merged, and I'll rebase this on new master.

**Comment by loot-king** [comment]
😘

**Comment by seratch** [comment]
I'm sorry the team took a very long time to respond to this. I'm still not sure if this approach is the best for addressing #32 yet. Allow me to hold off making any decisions about this for now.

**Comment by Lobosque** [comment]
@seratch while you decide on what the best approach is, is there any way at all to access the request header while handling an event?

**Comment by seratch** [comment]
@Lobosque 
>@seratch while you decide on what the best approach is, is there any way at all to access the request header while handling an event?

As `request` in Flask is a thread-local value, you can access it just by importing it. 

```python
import os
from flask import request
from slackeventsapi import SlackEventAdapter

slack_signing_secret = os.environ["SLACK_SIGNING_SECRET"]
slack_events_adapter = SlackEventAdapter(slack_signing_secret, "/slack/events")

# Example reaction emoji echo
@slack_events_adapter.on("reaction_added")
def reaction_added(event_data):
    print(request.headers)
    event = event_data["event"]
```

After leaving the above comment, I came to think that directly accessing `request` is totally fine because this project doesn't have plans to support any other frameworks apart from Flask. 

>NB: A side-effect of this is that all event handlers of the same type must have the same number of arguments!

Considering this disadvantage, I think we don't have a strong reason to merge this PR's changes.

**Comment by seratch** [comment]
As I mentioned in the last comment, you can access Flask's thread-local request object. Let me close this pull request. Thanks for taking the time to send it.

**Pull request closed without merging**
