### PR TITLE
Remove Python 2.7 compatibility

### LINKED ISSUE #95: itsdangerous package conflict with latest version of flask
### Description

The latest version of Flask (2.0.1) released on `2021-05-21` requires `itsdangerous>=2.0` this package required `itsdangerous<2` can this be safely changed so we can install the latest version of Flask

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slackeventsapi version: `2.2.1`
python version: 3.7
OS version(s): Mac OS 10.15.7

#### Steps to reproduce:

1. Using Pipenv for depency resolution. `pipenv install flask slackeventsapi`
2. 

#### Actual result:

```
Resolving dependencies...
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches itsdangerous<2,>=2.0 (from slackeventsapi==2.2.1->-r /var/folders/l2/z3fcfqdn6g56xqzyp36r6yyc0000gq/T/pipenv9_syt5ffrequirements/pipenv-4_xicpka-constraints.txt (line 14))
Tried: 0.9, 0.9.1, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 1.1.0, 1.1.0, 2.0.0, 2.0.0, 2.0.1, 2.0.1
Skipped pre-versions: 2.0.0a1, 2.0.0a1, 2.0.0rc1, 2.0.0rc1, 2.0.0rc2, 2.0.0rc2
There are incompatible versions in the resolved dependencies:
  itsdangerous<2 (from slackeventsapi==2.2.1->-r /var/folders/l2/z3fcfqdn6g56xqzyp36r6yyc0000gq/T/pipenv9_syt5ffrequirements/pipenv-4_xicpka-constraints.txt (line 14))
  itsdangerous>=2.0 (from flask==2.0.1->-r /var/folders/l2/z3fcfqdn6g56xqzyp36r6yyc0000gq/T/pipenv9_syt5ffrequirements/pipenv-4_xicpka-constraints.txt (line 6))
```

### PR DESCRIPTION
**Pull request by antonio-te**
###  Summary

Fixes #95.

- Remove example/python2
- Make travis and tox pyenvs match setup.py
- Revert to built-in open in setup.py
- Remove caps on transitive dependencies in setup.py

I thought of including a change to fully fix `tox`, but it seems unused and I didn't want to do too many unrelated things in the PR. Anyway, after the following diff, `tox` shows a passing result:

```diff
diff --git a/tox.ini b/tox.ini
index afdfad4..29d9a49 100644
--- a/tox.ini
+++ b/tox.ini
@@ -14 +13,0 @@ deps =
-    -r{toxinidir}/requirements.txt
```

### Requirements (place an `x` in each `[ ]`)

* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/python-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by seratch** [comment]
Hi @antonio-te, thanks for taking the time to make this contribution!

* Would you mind signing our CLA? Without having it, we are unable to have your changes in this repo
* You're right about tox. It is no longer used and we are happy to remove related files. But I agree that we can have minimum changes in this PR. The currrent fix looks great to me.

Once your fix is merged, we will release a new version - 3.0.0.

**Comment by antonio-te** [comment]
> Would you mind signing our CLA? Without having it, we are unable to have your changes in this repo

I wouldn't mind (I read it top-to-bottom, in fact), but I haven't had the occasion to sign one during the course of my work so I'm checking with my team to make doubly sure it's A-OK.

**Comment by antonio-te** [comment]
Apologies for the delay; I've gained approval to sign the CLA, and did so just now.

**Comment by seratch** [comment]
@antonio-te Thanks for working on this! After cleaning up a bit more, we will release v3.0 shortly.

**Pull request merged**
